#!/bin/bash
# SOFT DELETE - QUICK COMMANDS REFERENCE
# Copy-paste commands ini untuk testing soft delete functionality

echo "=========================================="
echo "SOFT DELETE COMMANDS REFERENCE"
echo "=========================================="

# STEP 1: RUN MIGRATIONS
echo ""
echo "STEP 1: Apply Database Migrations"
echo ">>> php artisan migrate"
echo ""
echo "Ini akan menambah kolom 'deleted_at' ke tabel:"
echo "  - events"
echo "  - tikets"
echo "  - kategoris"
echo "  - orders"

# STEP 2: CHECK MIGRATIONS STATUS
echo ""
echo "=========================================="
echo "STEP 2: Verify Migrations (Optional)"
echo ">>> php artisan migrate:status"
echo ">>> php artisan tinker"

# STEP 3: TESTING SOFT DELETE IN TINKER (Laravel Interactive Shell)
echo ""
echo "=========================================="
echo "STEP 3: Test Soft Delete di Tinker"
echo ""
echo "Buka terminal dan jalankan:"
echo ">>> php artisan tinker"
echo ""
echo "Kemudian copy-paste commands berikut:"
echo ""
echo "--- TEST 1: Create & View Event ---"
echo "\$event = App\\Models\\Event::find(1);  // Get existing event"
echo "\$event;  // Show event details"
echo ""
echo "--- TEST 2: Soft Delete Event ---"
echo "\$event->delete();  // Soft delete - set deleted_at = NOW()"
echo "\$event;  // Show deleted_at is now set"
echo ""
echo "--- TEST 3: Normal Query (Exclude Deleted) ---"
echo "App\\Models\\Event::whereNull('deleted_at')->count();  // Should decrease by 1"
echo ""
echo "--- TEST 4: View Only Deleted ---"
echo "\$deleted = App\\Models\\Event::onlyTrashed()->get();  // Get deleted events"
echo "\$deleted;  // Show deleted events"
echo ""
echo "--- TEST 5: View All Including Deleted ---"
echo "\$all = App\\Models\\Event::withTrashed()->get();  // All events"
echo "\$all->count();  // Same as before delete"
echo ""
echo "--- TEST 6: Restore Event ---"
echo "\$event->restore();  // Restore deleted event"
echo "\$event;  // Show deleted_at is now NULL again"
echo ""
echo "--- TEST 7: Permanent Delete (Force Delete) ---"
echo "\$event->forceDelete();  // Permanently delete from database"
echo "App\\Models\\Event::find(1);  // Will return null"
echo ""

# STEP 4: DATABASE QUERIES
echo ""
echo "=========================================="
echo "STEP 4: Database Queries (MySQL/SQLite)"
echo ""
echo "--- View Database Records ---"
echo "SELECT * FROM events;  // All including deleted"
echo ""
echo "--- View Only Active Records ---"
echo "SELECT * FROM events WHERE deleted_at IS NULL;  // Active only"
echo ""
echo "--- View Only Deleted Records ---"
echo "SELECT * FROM events WHERE deleted_at IS NOT NULL;  // Deleted only"
echo ""
echo "--- Restore Record via SQL ---"
echo "UPDATE events SET deleted_at = NULL WHERE id = 1;  // Restore by id"
echo ""
echo "--- Permanently Delete via SQL ---"
echo "DELETE FROM events WHERE id = 1;  // Force delete"
echo ""

# STEP 5: TESTING IN WEB UI
echo ""
echo "=========================================="
echo "STEP 5: Test in Web UI"
echo ""
echo "1. Go to: http://localhost:8000/admin/categories"
echo "2. You should see 2 tabs: 'Kategori Aktif' and 'Kategori Dihapus'"
echo "3. Click 'Hapus' on any category"
echo "4. Category should move to 'Kategori Dihapus' tab"
echo "5. Click 'Pulihkan' to restore"
echo "6. Category should move back to 'Kategori Aktif' tab"
echo ""
echo "Repeat for:"
echo "  - http://localhost:8000/admin/events"
echo "  - http://localhost:8000/admin/tickets"
echo "  - http://localhost:8000/admin/histories"
echo ""

# STEP 6: ARTISAN COMMANDS
echo ""
echo "=========================================="
echo "STEP 6: Useful Artisan Commands"
echo ""
echo "--- Fresh Migration (Reset & Remigrate) ---"
echo "php artisan migrate:fresh  # WARNING: Deletes all data!"
echo ""
echo "--- Rollback Last Migration ---"
echo "php artisan migrate:rollback"
echo ""
echo "--- Rollback All Migrations ---"
echo "php artisan migrate:reset  # WARNING: Deletes all data!"
echo ""
echo "--- Clear All Cache ---"
echo "php artisan cache:clear"
echo "php artisan config:clear"
echo ""

# STEP 7: TROUBLESHOOTING
echo ""
echo "=========================================="
echo "TROUBLESHOOTING"
echo ""
echo "ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleted_at'"
echo "FIX: Run migrations: php artisan migrate"
echo ""
echo "ERROR: Route not found for restore"
echo "FIX: Check routes are added in routes/web.php"
echo ""
echo "ERROR: View not showing deleted items"
echo "FIX: Verify controller passes \$deletedXXX variable to view"
echo ""
echo "ERROR: Data not restoring"
echo "FIX: Ensure Model has 'use SoftDeletes' trait"
echo ""

# STEP 8: VIEW UPDATE CHECKLIST
echo ""
echo "=========================================="
echo "FILES YANG PERLU DIUPDATE (BLADE TEMPLATES)"
echo ""
echo "1. resources/views/pages-admin/kategori.blade.php"
echo "   Action: Add soft delete UI with restore button"
echo "   Guide: See SOFT_DELETE_VIEW_GUIDE.php"
echo ""
echo "2. resources/views/events/events.blade.php"
echo "   Action: Add soft delete UI with restore button"
echo "   Guide: See SOFT_DELETE_VIEW_GUIDE.php"
echo ""
echo "3. resources/views/eventshow.blade.php (Tikets)"
echo "   Action: Add soft delete UI with restore button"
echo "   Guide: See SOFT_DELETE_VIEW_GUIDE.php"
echo ""
echo "4. resources/views/histories/histories.blade.php"
echo "   Action: Add soft delete UI with restore button"
echo "   Guide: See SOFT_DELETE_VIEW_GUIDE.php"
echo ""

# FINAL
echo ""
echo "=========================================="
echo "DOKUMENTASI LENGKAP TERSEDIA DI:"
echo ""
echo "  📄 SOFT_DELETE_EXPLANATION.txt"
echo "     - Penjelasan teori & cara kerja detail"
echo "     - Database schema & SQL queries"
echo "     - Code examples"
echo ""
echo "  📄 SOFT_DELETE_VIEW_GUIDE.php"
echo "     - Contoh lengkap Blade templates"
echo "     - Copy-paste untuk setiap view"
echo "     - UI dengan delete & restore buttons"
echo ""
echo "  📄 SOFT_DELETE_IMPLEMENTATION_GUIDE.md"
echo "     - Step-by-step implementation"
echo "     - Checklist lengkap"
echo "     - Troubleshooting guide"
echo ""
echo "=========================================="
